name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 12 * * *"
env:
  TENANT_ID: ${{ secrets.TENANT_ID }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS  }}
  
jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm help

  Run-PSScriptAnalyzer-on-Windows:
    name: Run PSScript on Windows
    runs-on: windows-latest
    steps:
      - name: Install CLI
        shell: pwsh
        run: |
          #Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; Remove-Item .\AzureCLI.msi
          Write-Output "overall"
      - name: install communication services module
        shell: pwsh
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          Install-Module Az.Communication
          #Import-Module Az.Communication
      - name: connect to SPN
        shell: pwsh
        run: |
          $User = $env:CLIENT_ID
          $PWord = $env:CLIENT_SECRET
          $tenant = $env:TENANT_ID
          $Credential = New-Object -ArgumentList $User,$PWord -TypeName "System.Management.Automation.PSCredential"
          Connect-AzAccount -Credential $Credential -Tenant $tenant -ServicePrincipal
          #az login --service-principal -u $User -p $PWord --tenant $tenant
      - name: Send Email
        shell: pwsh
        run: |
          $connection = "endpoint=https://daily-report-demo.communication.azure.com/;accesskey=04LvQxrsosgOWMarfxjDhBt1rHXRGvQ7zBifqMuxiKWOifQh/wuWMrY/G/qCTZd1eeISzhJfybOkYcr3ju//+Q=="
          $sender = "DoNotReply@ad2873a6-3d24-45e2-8e26-5f80ef712436.azurecomm.net"
          $receiver = "martin.lee@nutrien.com"
          $subject = "Welcome to Azure Communication Services Email"
          $text = "test"
          az communication email send --connection-string $connection --sender $sender --subject $subject --to $receiver --text "($text)"
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: $env:AZURE_CREDENTIALS
          enable-AzPSSession: true
          
